library(data.table)

bridge_rows <- list(
  c("EA", "00", "All-items HICP", "00", "All-items HICP", "exact", "Already common aggregate."),
  c("EA", "0122", NA, "0121", NA, "correspondence", ""),
  c("EA", "0123", NA, "0121", NA, "correspondence", ""),
  c("EA", "0124", NA, "0121", NA, "correspondence", ""),
  c("EA", "0121", NA, "0122", NA, "correspondence", ""),
  c("EA", "0125", NA, "0122", NA, "correspondence", ""),
  c("EA", "0126", NA, "0122", NA, "correspondence", ""),
  c("EA", "0129", NA, "0122", NA, "correspondence", ""),
  c("EA", "0130", NA, "0122", NA, "correspondence", ""),
  c("EA", "0219", "Other alcoholic beverages", "021", "Alcoholic beverages", "manual_correction", "Corrects earlier assignment to tobacco."),
  c("EA", "022", "Alcohol production services", "021", "Alcoholic beverages", "manual_correction", "Alcohol production services belong with alcoholic beverages, not tobacco."),
  c("EA", "0220", "Alcohol production services", "021", "Alcoholic beverages", "manual_correction", "Alcohol production services belong with alcoholic beverages, not tobacco."),
  c("EA", "023", "Tobacco", "022", "Tobacco", "manual_correction", "Corrects ECOICOP v2 division shift."),
  c("EA", "0230", "Tobacco", "022", "Tobacco", "manual_correction", "Corrects ECOICOP v2 division shift."),
  c("EA", "024", "Narcotics", "023", "Narcotics", "manual_correction", "Corrects ECOICOP v2 division shift."),
  c("EA", "0240", "Narcotics", "023", "Narcotics", "manual_correction", "Corrects ECOICOP v2 division shift."),
  c("EA", "0521", NA, "0513", NA, "correspondence", ""),
  c("EA", "0522", NA, "052", NA, "rolled_up", ""),
  c("EA", "0540", NA, "054", NA, "rolled_up", ""),
  c("EA", "0553", NA, "0552", NA, "correspondence", ""),
  c("EA", "0614", NA, "0613", NA, "correspondence", ""),
  c("EA", "0631", NA, "063", NA, "rolled_up", ""),
  c("EA", "0632", NA, "063", NA, "rolled_up", ""),
  c("EA", "0641", NA, "063", NA, "manual_choice", ""),
  c("EA", "0642", NA, "063", NA, "manual_choice", ""),
  c("EA", "074", NA, "081", NA, "rolled_up", "Level-2 transport/communication shift."),
  c("EA", "0741", NA, "081", NA, "correspondence", ""),
  c("EA", "0749", NA, "081", NA, "correspondence", ""),
  c("EA", "082", "Software, excluding games", "0913", "Information processing equipment", "manual_correction", "Corrects assignment from communication equipment to information processing equipment."),
  c("EA", "0820", "Software, excluding games", "0913", "Information processing equipment", "manual_correction", "Corrects assignment from communication equipment to information processing equipment."),
  c("EA", "0811", NA, "0820", NA, "correspondence", ""),
  c("EA", "0812", NA, "0820", NA, "correspondence", ""),
  c("EA", "0819", NA, "0820", NA, "correspondence", ""),
  c("EA", "0814", NA, "0911", NA, "correspondence", ""),
  c("EA", "0813", NA, "0913", NA, "correspondence", ""),
  c("EA", "0815", NA, "0914", NA, "correspondence", ""),
  c("EA", "084", NA, "091", NA, "rolled_up", "Level-2 communication/recreation shift."),
  c("EA", "0841", NA, "0915", NA, "correspondence", ""),
  c("EA", "083", NA, "083", NA, "exact", "Kept to preserve level-2 communication aggregate before lower-level mapping."),
  c("EA", "0821", NA, "082", NA, "rolled_up", ""),
  c("EA", "0822", NA, "082", NA, "rolled_up", ""),
  c("EA", "0823", NA, "082", NA, "rolled_up", ""),
  c("EA", "0824", NA, "082", NA, "rolled_up", ""),
  c("EA", "0825", NA, "082", NA, "rolled_up", ""),
  c("EA", "0829", NA, "082", NA, "rolled_up", ""),
  c("EA", "0831", NA, "0830", NA, "correspondence", ""),
  c("EA", "0832", NA, "0830", NA, "correspondence", ""),
  c("EA", "0833", NA, "0830", NA, "correspondence", ""),
  c("EA", "0834", NA, "0830", NA, "correspondence", ""),
  c("EA", "0835", NA, "0830", NA, "correspondence", ""),
  c("EA", "0839", NA, "0830", NA, "correspondence", ""),
  c("EA", "0911", NA, "0912", NA, "correspondence", ""),
  c("EA", "0941", NA, "0915", NA, "correspondence", ""),
  c("EA", "0912", NA, "0921", NA, "correspondence", ""),
  c("EA", "0951", NA, "0922", NA, "correspondence", ""),
  c("EA", "0952", "Audiovisual media", "0914", "Recording media", "manual_correction", "Corrects assignment from newspapers/books/stationery to recording media."),
  c("EA", "09520", "Audiovisual media", "0914", "Recording media", "manual_correction", "Corrects assignment from newspapers/books/stationery to recording media."),
  c("EA", "0942", NA, "0923", NA, "correspondence", ""),
  c("EA", "0921", NA, "0931", NA, "correspondence", ""),
  c("EA", "0922", NA, "0932", NA, "correspondence", ""),
  c("EA", "0931", NA, "0933", NA, "correspondence", ""),
  c("EA", "0943", "Hire and repair of games, toys and hobby-related articles", "0931", "Games, toys and hobbies", "manual_correction", "Corrects earlier assignment to gardens, plants and flowers."),
  c("EA", "0932", NA, "0934", NA, "correspondence", ""),
  c("EA", "0945", NA, "0935", NA, "correspondence", ""),
  c("EA", "0944", "Hire and repair of sporting, camping and open-air recreational equipment", "0932", "Equipment for sport, camping and open-air recreation", "manual_choice", "Single-code operational choice for a correspondence that can be split across v1 codes."),
  c("EA", "0946", NA, "0941", NA, "correspondence", ""),
  c("EA", "0947", "Games of chance", "0943", "Games of chance", "manual_correction", "Corrects earlier assignment to recreational and sporting services."),
  c("EA", "0961", NA, "0942", NA, "correspondence", ""),
  c("EA", "0962", NA, "0942", NA, "correspondence", ""),
  c("EA", "0963", NA, "0942", NA, "correspondence", ""),
  c("EA", "0969", NA, "0942", NA, "correspondence", ""),
  c("EA", "0971", NA, "0951", NA, "correspondence", ""),
  c("EA", "0972", NA, "0952", NA, "correspondence", ""),
  c("EA", "0973", NA, "0953", NA, "correspondence", ""),
  c("EA", "0974", NA, "0954", NA, "correspondence", ""),
  c("EA", "0980", NA, "096", NA, "rolled_up", ""),
  c("EA", "1010", NA, "101", NA, "rolled_up", ""),
  c("EA", "1020", NA, "102", NA, "rolled_up", ""),
  c("EA", "1030", NA, "103", NA, "rolled_up", ""),
  c("EA", "1040", NA, "104", NA, "rolled_up", ""),
  c("EA", "1050", NA, "105", NA, "rolled_up", ""),
  c("EA", "1120", NA, "112", NA, "rolled_up", ""),
  c("EA", "13", NA, "12", NA, "rolled_up", "ECOICOP v2 division 13 belongs to v1 division 12."),
  c("EA", "131", NA, "121", NA, "rolled_up", "ECOICOP v2 division 13 belongs to v1 division 12."),
  c("EA", "132", NA, "123", NA, "rolled_up", "ECOICOP v2 division 13 belongs to v1 division 12."),
  c("EA", "133", NA, "124", NA, "rolled_up", "ECOICOP v2 division 13 belongs to v1 division 12."),
  c("EA", "139", NA, "127", NA, "rolled_up", "ECOICOP v2 division 13 belongs to v1 division 12."),
  c("EA", "1311", NA, "1212", NA, "correspondence", ""),
  c("EA", "1312", NA, "1213", NA, "correspondence", ""),
  c("EA", "1321", NA, "1231", NA, "correspondence", ""),
  c("EA", "1322", NA, "1232", NA, "correspondence", ""),
  c("EA", "1329", NA, "1232", NA, "correspondence", ""),
  c("EA", "1213", NA, "1252", NA, "correspondence", ""),
  c("EA", "1212", NA, "1253", NA, "correspondence", ""),
  c("EA", "1214", NA, "1254", NA, "correspondence", ""),
  c("EA", "1219", NA, "1255", NA, "correspondence", ""),
  c("EA", "1330", NA, "124", NA, "rolled_up", ""),
  c("EA", "1222", NA, "126", NA, "rolled_up", ""),
  c("EA", "1229", NA, "126", NA, "rolled_up", ""),
  c("EA", "1313", "Hairdressing salons and personal grooming establishments", "1211", "Hairdressing salons and personal grooming establishments", "manual_correction", "Corrects earlier assignment to other services n.e.c."),
  c("EA", "13131", "Hairdressing", "1211", "Hairdressing salons and personal grooming establishments", "manual_correction", "Corrects earlier assignment to other services n.e.c."),
  c("EA", "13132", "Personal grooming treatments", "1211", "Hairdressing salons and personal grooming establishments", "manual_correction", "Corrects earlier assignment to other services n.e.c."),
  c("EA", "1390", NA, "127", NA, "manual_choice", "Operational choice; correspondence may include excluded/non-HICP services.")
)

ecoicop_v2_to_v1_bridge <- data.table::rbindlist(lapply(bridge_rows, function(x) {
  data.table::data.table(
    country = x[[1]],
    coicop_v2 = x[[2]],
    label_v2 = x[[3]],
    coicop_v1 = x[[4]],
    label_v1 = x[[5]],
    mapping_type = x[[6]],
    source = "Package operational ECOICOP v2 to ECOICOP v1 bridge",
    note = x[[7]]
  )
}))

ecoicop_v2_to_v1_bridge[, `:=`(
  coicop_v2_level = data.table::fifelse(coicop_v2 == "00", 0L, nchar(coicop_v2) - 1L),
  coicop_v1_level = data.table::fifelse(coicop_v1 == "00", 0L, nchar(coicop_v1) - 1L)
)]
data.table::setcolorder(
  ecoicop_v2_to_v1_bridge,
  c(
    "country", "coicop_v2", "label_v2", "coicop_v2_level",
    "coicop_v1", "label_v1", "coicop_v1_level",
    "mapping_type", "source", "note"
  )
)
data.table::setorder(ecoicop_v2_to_v1_bridge, country, coicop_v2)

save(
  ecoicop_v2_to_v1_bridge,
  file = file.path("data", "ecoicop_v2_to_v1_bridge.rda"),
  compress = "xz"
)
