#!/usr/bin/env Rscript

# Export paper tables from package calculations, following their order in main.tex.

script_file <- grep("^--file=", commandArgs(FALSE), value = TRUE)
script_file <- if (length(script_file)) sub("^--file=", "", script_file[[1]]) else
  "scripts/paper_exports/build_paper_tables.R"
package_root <- normalizePath(file.path(dirname(script_file), "..", ".."), mustWork = FALSE)
paper_repo <- Sys.getenv(
  "INFLATIONINEQUALITY_PAPER_REPO",
  file.path(dirname(package_root), "inflation-inequality-paper")
)
tables_dir <- file.path(paper_repo, "tables")
manifest_path <- file.path(tables_dir, "_paper_table_exports_manifest.csv")

dir.create(tables_dir, recursive = TRUE, showWarnings = FALSE)

if (requireNamespace("pkgload", quietly = TRUE) &&
    file.exists(file.path(package_root, "DESCRIPTION"))) {
  pkgload::load_all(package_root, quiet = TRUE)
} else {
  library(inflationinequality)
}

suppressPackageStartupMessages({
  library(data.table)
})

latex_escape <- function(x) {
  x <- as.character(x)
  x <- gsub("\\\\", "\\\\textbackslash{}", x)
  x <- gsub("([#$%&_{}])", "\\\\\\1", x, perl = TRUE)
  x
}

format_number <- function(x, digits = 2) {
  ifelse(is.na(x), "", formatC(x, format = "f", digits = digits))
}

write_latex_table <- function(dt, file, caption, label, notes = NULL,
                              numeric_digits = 2) {
  out <- file.path(tables_dir, file)
  display <- copy(dt)
  for (j in names(display)) {
    if (is.numeric(display[[j]])) {
      display[, (j) := format_number(get(j), numeric_digits)]
    } else {
      display[, (j) := latex_escape(get(j))]
    }
  }

  align <- paste0(
    "l",
    paste(rep("r", max(ncol(display) - 1, 0)), collapse = "")
  )
  header <- paste(latex_escape(names(display)), collapse = " & ")
  rows <- apply(display, 1, paste, collapse = " & ")

  lines <- c(
    "\\begin{table}[htbp]",
    "\\centering",
    paste0("\\caption{", latex_escape(caption), "}"),
    paste0("\\label{", latex_escape(label), "}"),
    paste0("\\begin{tabular}{", align, "}"),
    "\\toprule",
    paste0(header, " \\\\"),
    "\\midrule",
    paste0(rows, " \\\\"),
    "\\bottomrule",
    "\\end{tabular}"
  )
  if (!is.null(notes) && nzchar(notes)) {
    lines <- c(
      lines,
      "\\begin{flushleft}",
      paste0("\\footnotesize{\\emph{Notes:} ", latex_escape(notes), "}"),
      "\\end{flushleft}"
    )
  }
  lines <- c(lines, "\\end{table}")
  writeLines(lines, out, useBytes = TRUE)
  out
}

todo <- function(reason) {
  force(reason)
  function() {
    stop(reason, call. = FALSE)
  }
}

table_registry <- list(
  list(
    order = 1,
    file = "tab_FR_decile_validation_summary.tex",
    caption = "Comparison with annual inflation by decile: France",
    status = "implemented",
    builder = function() {
      stats_path <- file.path(
        package_root,
        "man",
        "figures",
        "france-insee-decile-published-vs-recalculated-D1-D10-2010-2023-stats.csv"
      )
      if (!file.exists(stats_path)) {
        stop(
          "Missing decile validation stats. Run scripts/plot_fr_d1_d10_inflation_level3.R first.",
          call. = FALSE
        )
      }
      out <- fread(stats_path)
      out[, decile_number := as.integer(gsub("[^0-9]", "", category))]
      setorder(out, decile_number)
      out <- out[
        ,
        .(
          Decile = paste0("D", decile_number),
          `Mean offset` = mean_offset,
          `Mean absolute offset` = mean_abs_offset,
          `Maximum absolute offset` = max_abs_offset
        )
      ]
      write_latex_table(
        out,
        "tab_FR_decile_validation_summary.tex",
        "Comparison with annual inflation by decile: France",
        "tab:fr-decile-validation",
        paste(
          "Offsets are recalculated minus published annual inflation rates,",
          "in percentage points. Source CSV is generated by",
          "scripts/plot_fr_d1_d10_inflation_level3.R."
        ),
        numeric_digits = 3
      )
    }
  ),
  list(
    order = 2,
    file = "tab_EU6_aggregation_bias_level1_level2.tex",
    caption = "Aggregation bias between COICOP levels 1 and 2",
    status = "implemented",
    builder = function() {
      countries <- c("DE", "FR", "IT", "ES", "NL", "BE")
      out <- rbindlist(lapply(countries, function(country) {
        calculate_aggregation_bias(
          country,
          "income",
          coarse_level = 1,
          fine_level = 2,
          start_year = 2019
        )
      }), use.names = TRUE, fill = TRUE)
      out <- out[
        ,
        .(
          Country = country,
          `Coarse level` = coarse_level,
          `Fine level` = fine_level,
          `Coarse gap` = coarse_gap,
          `Fine gap` = fine_gap,
          `Aggregation bias` = aggregation_bias
        )
      ]
      write_latex_table(
        out,
        "tab_EU6_aggregation_bias_level1_level2.tex",
        "Aggregation bias between COICOP levels 1 and 2",
        "tab:aggregation-bias-level1-level2",
        paste(
          "The table reports aggregation_bias =",
          "inflation_gap_coicop_upperdigit - inflation_gap_coicop_lowerdigit.",
          "Growth rates are annualized over the available period from 2019."
        ),
        numeric_digits = 3
      )
    }
  ),
  list(
    order = 3,
    file = "tab_FR_substitution_bias_income_level2.tex",
    caption = "Upper-level substitution bias by income group, France, COICOP level 2",
    status = "implemented",
    builder = function() {
      out <- calculate_substitution_bias(
        "FR",
        "income",
        level = 2,
        start_year = 2019
      )
      out <- out[
        ,
        .(
          Group = category,
          `Chained Laspeyres growth` = chained_laspeyres_growth,
          `Chained Tornqvist growth` = chained_toernqvist_growth,
          `Substitution bias` = substitution_bias
        )
      ]
      write_latex_table(
        out,
        "tab_FR_substitution_bias_income_level2.tex",
        "Upper-level substitution bias by income group, France, COICOP level 2",
        "tab:fr-substitution-bias",
        paste(
          "Substitution bias is defined as chained_laspeyres_growth",
          "minus chained_tornqvist_growth, in percentage points.",
          "Growth rates are annualized over the available period from 2019."
        ),
        numeric_digits = 2
      )
    }
  )
)

run_exports <- function(registry = table_registry, overwrite = TRUE) {
  manifest <- rbindlist(lapply(registry, function(item) {
    out_file <- file.path(tables_dir, item$file)
    if (!isTRUE(overwrite) && file.exists(out_file)) {
      return(data.table(
        order = item$order, file = item$file, caption = item$caption,
        status = "kept_existing", message = "File exists and overwrite is FALSE."
      ))
    }
    if (!identical(item$status, "implemented")) {
      return(data.table(
        order = item$order, file = item$file, caption = item$caption,
        status = "skipped", message = "No package-native builder yet."
      ))
    }
    result <- tryCatch(
      {
        item$builder()
        data.table(
          order = item$order, file = item$file, caption = item$caption,
          status = "exported", message = normalizePath(out_file, mustWork = FALSE)
        )
      },
      error = function(e) {
        data.table(
          order = item$order, file = item$file, caption = item$caption,
          status = "failed", message = conditionMessage(e)
        )
      }
    )
    result
  }), use.names = TRUE, fill = TRUE)

  fwrite(manifest, manifest_path)
  print(manifest)
  invisible(manifest)
}

if (!identical(Sys.getenv("INFLATIONINEQUALITY_SKIP_RUN_EXPORTS"), "true")) {
  run_exports()
}
