#' Simulate electricity policy scenarios
#'
#' @description
#' `simulate_energy_policy()` implements the policy-simulation
#' framework used in the CAE energy-policy section.
#'
#' The package implementation uses the household-budget data available in
#' `inflationinequality`. By default, this is the bundled INSEE Budget de
#' famille 2017 France level-3 HBS by standard-of-living decile. The CAE
#' article uses household microdata, so within-decile dispersion figures are
#' approximated here by group-level values only.
#'
#' @param country Country used when `custom_hbs` is not supplied. `"FR"` uses
#'   the bundled INSEE Budget de famille HBS. `"ES"` uses the compact 2020 INE
#'   EPF object generated by `scripts/build_es_epf_2020_hbs.R`, when available.
#' @param custom_hbs Optional `"hbs"` object. If omitted, `country` determines
#'   the package HBS object to use.
#' @param income_groups France INSEE grouping to use when `custom_hbs` is not
#'   supplied. `"decile"` is closest to the CAE tables.
#' @param electricity_coicop COICOP code for electricity expenditure.
#' @param price_shock Log price shock used in the first-order equivalent
#'   variation formula. The CAE exercise uses `0.30`.
#' @param elasticity Electricity demand elasticity. The CAE exercise uses `-0.2`.
#' @param reference_cost_billion Public cost, in billions of euros, of the
#'   all-household price-regulation scenario A.1. The CAE exercise fixes it at `20`.
#' @param household_electricity_share Share of household electricity consumption
#'   in total electricity consumption, used to convert household demand response
#'   into aggregate electricity demand response. The CAE exercise's 6% household
#'   response and 2% aggregate response imply about `1 / 3`.
#'
#' @return A list with:
#' \describe{
#'   \item{descriptive}{Group-level electricity expenditure shares and
#'   equivalent variations.}
#'   \item{household_policies}{Household-level/group-level policy transfers.}
#'   \item{tables}{Replications of the CAE comparison tables.}
#'   \item{plots}{Group-level replications/approximations of Figures 6 to 9.}
#'   \item{metadata}{Assumptions and caveats.}
#' }
#'
#' @examples
#' res <- simulate_energy_policy()
#' res$tables$all_households
#' res$tables$below_median
#' res$plots$figure6
#'
#' @importFrom data.table :=
#' @export
simulate_energy_policy <- function(country = c("FR", "ES"),
                                   custom_hbs = NULL,
                                   income_groups = c("decile", "quintile"),
                                   electricity_coicop = "0451",
                                   price_shock = 0.30,
                                   elasticity = -0.2,
                                   reference_cost_billion = 20,
                                   household_electricity_share = 1 / 3) {
  country <- match.arg(toupper(country), c("FR", "ES"))
  income_groups <- match.arg(income_groups)
  hbs_obj <- if (is.null(custom_hbs)) {
    load_energy_policy_hbs(country, income_groups)
  } else {
    custom_hbs
  }

  validate_energy_policy_inputs(
    hbs_obj = hbs_obj,
    electricity_coicop = electricity_coicop,
    price_shock = price_shock,
    elasticity = elasticity,
    reference_cost_billion = reference_cost_billion,
    household_electricity_share = household_electricity_share
  )

  descriptive <- build_energy_policy_descriptive_inputs(
    hbs_obj = hbs_obj,
    electricity_coicop = electricity_coicop,
    price_shock = price_shock
  )
  policies <- build_energy_policy_transfers(
    descriptive = descriptive,
    price_shock = price_shock
  )

  tables <- list(
    all_households = build_energy_policy_table(
      policies = policies,
      scope = "all",
      reference_cost_billion = reference_cost_billion,
      elasticity = elasticity,
      price_shock = price_shock,
      household_electricity_share = household_electricity_share
    ),
    below_median = build_energy_policy_table(
      policies = policies,
      scope = "below_median",
      reference_cost_billion = reference_cost_billion,
      elasticity = elasticity,
      price_shock = price_shock,
      household_electricity_share = household_electricity_share
    )
  )

  plots <- build_energy_policy_plots(descriptive, policies)

  structure(
    list(
      descriptive = descriptive,
      household_policies = policies,
      tables = tables,
      plots = plots,
      metadata = list(
        source = "CAE electricity-policy framework, implemented with package HBS group data.",
        hbs_country = hbs_obj$country,
        hbs_category = hbs_obj$category,
        hbs_categories = hbs_obj$categories,
        hbs_years = range(hbs_obj$dt$year),
        electricity_coicop = electricity_coicop,
        price_shock = price_shock,
        elasticity = elasticity,
        reference_cost_billion = reference_cost_billion,
        household_electricity_share = household_electricity_share,
        caveat = paste(
          "The CAE exercise uses household microdata.",
          "This package implementation uses group-level HBS expenditure means;",
          "within-decile p25/p75 dispersion and household-level overcompensation shares",
          "are therefore approximated by available groups."
        ),
        not_replicated = paste(
          "The CAE table on past and present consumption uses Credit Mutuel Alliance federale account data",
          "to correlate past and present consumption.",
          "Those microdata are not included in the package."
        )
      )
    ),
    class = "energy_policy"
  )
}

load_energy_policy_hbs <- function(country, income_groups) {
  if (identical(country, "FR")) {
    return(load_france_insee_hbs_level3("income", income_groups = income_groups))
  }

  hbs_obj <- load_spain_epf_2020_hbs_if_available("income")
  if (!is.null(hbs_obj)) {
    return(hbs_obj)
  }

  stop(
    "Spain EPF 2020 HBS data are not available. ",
    "Run scripts/build_es_epf_2020_hbs.R after downloading INE datos_2020.zip, ",
    "or pass a custom_hbs object.",
    call. = FALSE
  )
}

load_spain_epf_2020_hbs_if_available <- function(category = "income") {
  if (!file.exists(spain_epf_2020_hbs_level3_path(category))) {
    return(NULL)
  }
  load_spain_epf_2020_hbs_level3(category)
}

validate_energy_policy_inputs <- function(hbs_obj,
                                          electricity_coicop,
                                          price_shock,
                                          elasticity,
                                          reference_cost_billion,
                                          household_electricity_share) {
  if (!inherits(hbs_obj, "hbs")) {
    stop("custom_hbs must be an 'hbs' object.")
  }
  if (!hbs_obj$category == "income") {
    stop("Energy policy simulations require income-group HBS data.")
  }
  if (!is.character(electricity_coicop) || length(electricity_coicop) != 1 ||
      is.na(electricity_coicop)) {
    stop("electricity_coicop must be a single COICOP code.")
  }
  if (!electricity_coicop %in% hbs_obj$dt$coicop) {
    stop("electricity_coicop was not found in the HBS data.")
  }
  validate_energy_policy_scalar(price_shock, "price_shock")
  validate_energy_policy_scalar(elasticity, "elasticity")
  validate_energy_policy_scalar(reference_cost_billion, "reference_cost_billion")
  validate_energy_policy_scalar(household_electricity_share, "household_electricity_share")
  if (price_shock < 0) {
    stop("price_shock must be non-negative.")
  }
  if (reference_cost_billion < 0) {
    stop("reference_cost_billion must be non-negative.")
  }
  if (household_electricity_share < 0 || household_electricity_share > 1) {
    stop("household_electricity_share must be between 0 and 1.")
  }
}

validate_energy_policy_scalar <- function(x, arg) {
  if (!is.numeric(x) || length(x) != 1 || is.na(x)) {
    stop(arg, " must be a single numeric value.")
  }
}

build_energy_policy_descriptive_inputs <- function(hbs_obj, electricity_coicop, price_shock) {
  hbs_dt <- data.table::copy(hbs_obj$dt)
  leaf_level <- max(nchar(hbs_dt$coicop), na.rm = TRUE)
  group_order <- data.table::data.table(
    category = hbs_obj$categories,
    group_rank = seq_along(hbs_obj$categories),
    population_weight = 1 / length(hbs_obj$categories)
  )

  total <- hbs_dt[
    nchar(coicop) == leaf_level,
    .(total_consumption = sum(consumption, na.rm = TRUE)),
    by = .(category, year)
  ]
  electricity <- hbs_dt[
    coicop == electricity_coicop,
    .(electricity_expenditure = sum(consumption, na.rm = TRUE)),
    by = .(category, year)
  ]

  out <- merge(total, electricity, by = c("category", "year"))
  out <- merge(out, group_order, by = "category", all.x = TRUE)
  data.table::setorder(out, group_rank, year)
  out[, `:=`(
    electricity_share = electricity_expenditure / total_consumption,
    below_median = group_rank <= length(hbs_obj$categories) / 2
  )]
  out[, `:=`(
    equivalent_variation = electricity_share * price_shock,
    equivalent_variation_eur = electricity_expenditure * price_shock
  )]
  out[]
}

build_energy_policy_transfers <- function(descriptive, price_shock) {
  dt <- data.table::copy(descriptive)
  need <- dt$equivalent_variation_eur
  weighted_mean_all <- weighted.mean(need, dt$population_weight)
  eligible <- dt$below_median
  weighted_mean_eligible <- weighted.mean(need[eligible], dt$population_weight[eligible])

  scenarios <- data.table::rbindlist(list(
    energy_policy_rows(dt, "A1", "Prix regule", TRUE, "price_regulation", need),
    energy_policy_rows(dt, "B1", "Transfert forfaitaire", TRUE, "lump_sum", rep(weighted_mean_all, nrow(dt))),
    energy_policy_rows(dt, "C1", "Transfert en fonction de la consommation passee", TRUE, "past_consumption", need),
    energy_policy_rows(dt, "A2", "Prix regule", eligible, "price_regulation", data.table::fifelse(eligible, need, 0)),
    energy_policy_rows(dt, "B2", "Transfert forfaitaire", eligible, "lump_sum", data.table::fifelse(eligible, weighted_mean_eligible, 0)),
    energy_policy_rows(dt, "C2", "Transfert en fonction de la consommation passee", eligible, "past_consumption", data.table::fifelse(eligible, need, 0))
  ), use.names = TRUE)

  scenarios[, `:=`(
    unmet_need = pmax(equivalent_variation_eur - transfer_eur, 0),
    excess_transfer = pmax(transfer_eur - equivalent_variation_eur, 0),
    net_compensation = transfer_eur - equivalent_variation_eur
  )]
  scenarios[]
}

energy_policy_rows <- function(dt, scenario, label, eligible, policy_type, transfer) {
  out <- data.table::copy(dt)
  out[, `:=`(
    scenario = scenario,
    policy_label = label,
    policy_type = policy_type,
    eligible = eligible,
    transfer_eur = transfer
  )]
  out
}

build_energy_policy_table <- function(policies,
                                      scope,
                                      reference_cost_billion,
                                      elasticity,
                                      price_shock,
                                      household_electricity_share) {
  scenario_ids <- if (scope == "all") c("A1", "B1", "C1") else c("A2", "B2", "C2")
  eval_dt <- policies[scenario %in% scenario_ids]
  if (scope == "below_median") {
    eval_dt <- eval_dt[below_median == TRUE]
  }

  all_need <- policies[scenario == "A1", weighted_sum(equivalent_variation_eur, population_weight)]
  summary <- eval_dt[, {
    total_transfer <- weighted_sum(transfer_eur, population_weight)
    total_need_scope <- weighted_sum(equivalent_variation_eur, population_weight)
    over <- transfer_eur > equivalent_variation_eur
    under <- transfer_eur < equivalent_variation_eur
    eligible_need_share <- total_need_scope / all_need
    demand_response_household <- if (policy_type[1] == "price_regulation") {
      -elasticity * price_shock * eligible_need_share
    } else {
      0
    }
    .(
      policy_label = policy_label[1],
      aggregate_consumption_change_pct = 100 * household_electricity_share * demand_response_household,
      household_consumption_change_pct = 100 * demand_response_household,
      total_cost_billion = reference_cost_billion * total_transfer / all_need,
      public_spending_overcompensation_pct = pct(weighted_sum(excess_transfer, population_weight), total_transfer),
      public_spending_top_10_pct = if (scope == "below_median") 0 else {
        top_group <- max(group_rank)
        pct(
          weighted_sum(transfer_eur[group_rank == top_group], population_weight[group_rank == top_group]),
          total_transfer
        )
      },
      households_overcompensated_pct = pct(weighted_sum(as.numeric(over), population_weight), sum(population_weight)),
      mean_overcompensation_consumption_pct = if (any(over)) {
        weighted.mean(100 * excess_transfer[over] / total_consumption[over], population_weight[over])
      } else {
        0
      },
      households_undercompensated_pct = pct(weighted_sum(as.numeric(under), population_weight), sum(population_weight)),
      mean_undercompensation_consumption_pct = if (any(under)) {
        weighted.mean(100 * unmet_need[under] / total_consumption[under], population_weight[under])
      } else {
        0
      }
    )
  }, by = scenario]

  data.table::setorder(summary, scenario)
  summary[]
}

weighted_sum <- function(x, w) {
  sum(x * w, na.rm = TRUE)
}

pct <- function(x, denom) {
  if (is.na(denom) || denom == 0) {
    return(NA_real_)
  }
  100 * x / denom
}

build_energy_policy_plots <- function(descriptive, policies) {
  figure6 <- ggplot2::ggplot(
    descriptive,
    ggplot2::aes(x = group_rank, y = 100 * electricity_share)
  ) +
    ggplot2::geom_line(color = "#2f5d8c", linewidth = 0.7) +
    ggplot2::geom_point(color = "#2f5d8c", size = 2) +
    ggplot2::scale_x_continuous(
      breaks = descriptive$group_rank,
      labels = descriptive$category
    ) +
    ggplot2::labs(
      title = "Depenses d'electricite en fonction du niveau de vie",
      x = NULL,
      y = "Part dans la depense totale (%)"
    ) +
    ggplot2::theme_minimal(base_size = 11) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))

  figure7 <- ggplot2::ggplot(
    descriptive,
    ggplot2::aes(x = category, y = 100 * electricity_share)
  ) +
    ggplot2::geom_col(fill = "#7f9db9", width = 0.7) +
    ggplot2::labs(
      title = "Depenses d'electricite par groupe de niveau de vie",
      subtitle = "Approximation groupee : les percentiles intra-decile ne sont pas disponibles dans les donnees du package",
      x = NULL,
      y = "Part dans la depense totale (%)"
    ) +
    ggplot2::theme_minimal(base_size = 11) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))

  transfer_dt <- policies[scenario %in% c("A1", "C1")]
  figure8 <- ggplot2::ggplot(
    transfer_dt,
    ggplot2::aes(x = group_rank, y = transfer_eur, color = scenario)
  ) +
    ggplot2::geom_line(linewidth = 0.7) +
    ggplot2::geom_point(size = 2) +
    ggplot2::scale_x_continuous(
      breaks = descriptive$group_rank,
      labels = descriptive$category
    ) +
    ggplot2::labs(
      title = "Montants des transferts par niveau de vie",
      subtitle = "Scenarios A.1 et C.1",
      x = NULL,
      y = "Transfert moyen par menage",
      color = NULL
    ) +
    ggplot2::theme_minimal(base_size = 11) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))

  figure9 <- ggplot2::ggplot(
    transfer_dt,
    ggplot2::aes(x = category, y = transfer_eur, fill = scenario)
  ) +
    ggplot2::geom_col(position = "dodge", width = 0.7) +
    ggplot2::labs(
      title = "Transferts avec les mesures A.1 et C.1",
      subtitle = "Approximation groupee : pas de dispersion intra-decile sans microdonnees",
      x = NULL,
      y = "Transfert moyen par menage",
      fill = NULL
    ) +
    ggplot2::theme_minimal(base_size = 11) +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1))

  list(
    figure6 = figure6,
    figure7 = figure7,
    figure8 = figure8,
    figure9 = figure9
  )
}
